from defesaCivil.ocorrencias.models import *
from django.contrib import admin

admin.site.register(Bairro)
admin.site.register(ConstrucaoEncosta)
admin.site.register(TipoObra)
admin.site.register(EstadoConstrucao)
admin.site.register(Parede)
admin.site.register(Piso)
admin.site.register(Laje)
admin.site.register(Telhado)
admin.site.register(Cobertura)
admin.site.register(Coluna)
admin.site.register(Ocorrencia)
admin.site.register(Status)
admin.site.register(Assunto)
admin.site.register(Situacao)
admin.site.register(ModoConstrutivo)
admin.site.register(Viga)
admin.site.register(Origem)
admin.site.register(UsuarioRegistrador)
admin.site.register(Parecer)
